version: '2.4'

services:
  db:
    image: mysql #https://hub.docker.com/_/mysql
    container_name: upload-to-database-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - upload-to-database-container:/var/lib/mysql

volumes:
  upload-to-database-container:

